kind: pipeline
name: docker

steps:
  - name: build
    image: docker
    pull: true
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    environment:
      REGISTRY_USER:
        from_secret: REGISTRY_USER
      REGISTRY_PASS:
        from_secret: REGISTRY_PASS
      IMAGE_NAME:
        from_secret: IMAGE_NAME
    commands:
      - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
      - docker pull "$IMAGE_NAME" || true
      - docker build --cache-from "$IMAGE_NAME:latest" -t "$IMAGE_NAME" .
      - docker push "$IMAGE_NAME"
volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - prod
